config/routes.rb
Lab02Auth::Application.routes.draw do

  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  
  resources :users
  resources :user_types

  

  root :to => "users#index"

end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  # GET /user_types
  # GET /user_types.xml
  def index
    @user_types = UserType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_types }
    end
  end

  # GET /user_types/1
  # GET /user_types/1.xml
  def show
    @user_type = UserType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_type }
    end
  end

  # GET /user_types/new
  # GET /user_types/new.xml
  def new
    @user_type = UserType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_type }
    end
  end

  # GET /user_types/1/edit
  def edit
    @user_type = UserType.find(params[:id])
  end

  # POST /user_types
  # POST /user_types.xml
  def create
    @user_type = UserType.new(params[:user_type])

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to(@user_type, :notice => 'User type was successfully created.') }
        format.xml  { render :xml => @user_type, :status => :created, :location => @user_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_types/1
  # PUT /user_types/1.xml
  def update
    @user_type = UserType.find(params[:id])

    respond_to do |format|
      if @user_type.update_attributes(params[:user_type])
        format.html { redirect_to(@user_type, :notice => 'User type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1
  # DELETE /user_types/1.xml
  def destroy
    @user_type = UserType.find(params[:id])
    @user_type.destroy

    respond_to do |format|
      format.html { redirect_to(user_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/_form.html.erb
<%= form_for(@user_type) do |f| %>
  <% if @user_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_type.errors.count, "error") %> prohibited this user_type from being saved:</h2>

      <ul>
      <% @user_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_types/edit.html.erb
<h1>Editing user_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_type %> |
<%= link_to 'Back', user_types_path %>

app/views/user_types/index.html.erb
<h1>Listing user_types</h1>

<table>
  <tr>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_types.each do |user_type| %>
  <tr>
    <td><%= user_type.type %></td>
    <td><%= link_to 'Show', user_type %></td>
    <td><%= link_to 'Edit', edit_user_type_path(user_type) %></td>
    <td><%= link_to 'Destroy', user_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User type', new_user_type_path %>

app/views/user_types/new.html.erb
<h1>New user_type</h1>

<%= render 'form' %>

<%= link_to 'Back', user_types_path %>

app/views/user_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @user_type.type %>
</p>


<%= link_to 'Edit', edit_user_type_path(@user_type) %> |
<%= link_to 'Back', user_types_path %>